name: complete_advanced_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.4
  retrofit: ^3.3.1
  analyzer: ^5.1.0
  dio: ^4.0.6

  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15
  device_info_plus: ^8.0.0
  android_id: ^0.1.3+1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  lottie: ^2.0.0
  fl_country_code_picker: ^0.0.4
  image_picker: ^0.8.6
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  easy_localization: ^3.0.1
  flutter_phoenix: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.1
  retrofit_generator: ^4.2.0
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1-mdpi.svg
    - assets/images/onboarding_logo2-mdpi.svg
    - assets/images/onboarding_logo3-mdpi.svg
    - assets/images/onboarding_logo4.svg
    - assets/images/right_arrow_icon-mdpi.svg
    - assets/images/left_arrow_icon-mdpi.svg
    - assets/images/filled_circle-mdpi.svg
    - assets/images/not_filled_circle-mdpi.svg
    - assets/images/login_logo.svg
    - assets/images/contact_us_ic.svg
    - assets/images/invite_friends_ic.svg
    - assets/images/logout_ic.svg
    - assets/images/settings_chevron_icon.svg
    - assets/images/settings_ic.svg
    - assets/json/loading.json
    - assets/json/error.json
    - assets/json/empty.json
    - assets/json/success.json
    - assets/translations/



  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300